/* Generated by shiki-codegen. Do not edit directly. */
import type {
  DynamicImportLanguageRegistration,
  DynamicImportThemeRegistration,
  HighlighterGeneric,
} from "@shikijs/types";
import { createBundledHighlighter, createSingletonShorthands } from "@shikijs/core";
import { createJavaScriptRegexEngine } from "@shikijs/engine-javascript";

type BundledLanguage =
  | "awk"
  | "bat"
  | "batch"
  | "c"
  | "clojure"
  | "clj"
  | "cmake"
  | "coffee"
  | "coffeescript"
  | "cpp"
  | "c++"
  | "csharp"
  | "c#"
  | "cs"
  | "css"
  | "csv"
  | "dart"
  | "diff"
  | "docker"
  | "dockerfile"
  | "dotenv"
  | "elixir"
  | "erlang"
  | "erl"
  | "fish"
  | "fortran-fixed-form"
  | "f"
  | "for"
  | "f77"
  | "fortran-free-form"
  | "f90"
  | "f95"
  | "f03"
  | "f08"
  | "f18"
  | "fsharp"
  | "f#"
  | "fs"
  | "go"
  | "graphql"
  | "gql"
  | "groovy"
  | "haskell"
  | "hs"
  | "html"
  | "http"
  | "ini"
  | "properties"
  | "java"
  | "javascript"
  | "js"
  | "cjs"
  | "mjs"
  | "jinja"
  | "json"
  | "json5"
  | "jsonc"
  | "jsx"
  | "julia"
  | "jl"
  | "kotlin"
  | "kt"
  | "kts"
  | "latex"
  | "less"
  | "log"
  | "lua"
  | "make"
  | "makefile"
  | "markdown"
  | "md"
  | "nginx"
  | "nix"
  | "objective-c"
  | "objc"
  | "objective-cpp"
  | "perl"
  | "php"
  | "pkl"
  | "po"
  | "pot"
  | "potx"
  | "powershell"
  | "ps"
  | "ps1"
  | "proto"
  | "protobuf"
  | "python"
  | "py"
  | "r"
  | "rst"
  | "ruby"
  | "rb"
  | "rust"
  | "rs"
  | "sass"
  | "scala"
  | "scss"
  | "shellscript"
  | "bash"
  | "sh"
  | "shell"
  | "zsh"
  | "sql"
  | "ssh-config"
  | "stylus"
  | "styl"
  | "svelte"
  | "swift"
  | "system-verilog"
  | "terraform"
  | "tf"
  | "tfvars"
  | "toml"
  | "tsx"
  | "typescript"
  | "ts"
  | "cts"
  | "mts"
  | "vb"
  | "cmd"
  | "verilog"
  | "viml"
  | "vim"
  | "vimscript"
  | "vue"
  | "xml"
  | "yaml"
  | "yml"
  | "zig";
type BundledTheme = "github-light-default" | "github-dark-default";
type Highlighter = HighlighterGeneric<BundledLanguage, BundledTheme>;

const bundledLanguages = {
  awk: () => import("@shikijs/langs/awk"),
  bat: () => import("@shikijs/langs/bat"),
  batch: () => import("@shikijs/langs/bat"),
  c: () => import("@shikijs/langs/c"),
  clojure: () => import("@shikijs/langs/clojure"),
  clj: () => import("@shikijs/langs/clojure"),
  cmake: () => import("@shikijs/langs/cmake"),
  coffee: () => import("@shikijs/langs/coffee"),
  coffeescript: () => import("@shikijs/langs/coffee"),
  cpp: () => import("@shikijs/langs/cpp"),
  "c++": () => import("@shikijs/langs/cpp"),
  csharp: () => import("@shikijs/langs/csharp"),
  "c#": () => import("@shikijs/langs/csharp"),
  cs: () => import("@shikijs/langs/csharp"),
  css: () => import("@shikijs/langs/css"),
  csv: () => import("@shikijs/langs/csv"),
  dart: () => import("@shikijs/langs/dart"),
  diff: () => import("@shikijs/langs/diff"),
  docker: () => import("@shikijs/langs/docker"),
  dockerfile: () => import("@shikijs/langs/docker"),
  dotenv: () => import("@shikijs/langs/dotenv"),
  elixir: () => import("@shikijs/langs/elixir"),
  erlang: () => import("@shikijs/langs/erlang"),
  erl: () => import("@shikijs/langs/erlang"),
  fish: () => import("@shikijs/langs/fish"),
  "fortran-fixed-form": () => import("@shikijs/langs/fortran-fixed-form"),
  f: () => import("@shikijs/langs/fortran-fixed-form"),
  for: () => import("@shikijs/langs/fortran-fixed-form"),
  f77: () => import("@shikijs/langs/fortran-fixed-form"),
  "fortran-free-form": () => import("@shikijs/langs/fortran-free-form"),
  f90: () => import("@shikijs/langs/fortran-free-form"),
  f95: () => import("@shikijs/langs/fortran-free-form"),
  f03: () => import("@shikijs/langs/fortran-free-form"),
  f08: () => import("@shikijs/langs/fortran-free-form"),
  f18: () => import("@shikijs/langs/fortran-free-form"),
  fsharp: () => import("@shikijs/langs/fsharp"),
  "f#": () => import("@shikijs/langs/fsharp"),
  fs: () => import("@shikijs/langs/fsharp"),
  go: () => import("@shikijs/langs/go"),
  graphql: () => import("@shikijs/langs/graphql"),
  gql: () => import("@shikijs/langs/graphql"),
  groovy: () => import("@shikijs/langs/groovy"),
  haskell: () => import("@shikijs/langs/haskell"),
  hs: () => import("@shikijs/langs/haskell"),
  html: () => import("@shikijs/langs/html"),
  http: () => import("@shikijs/langs/http"),
  ini: () => import("@shikijs/langs/ini"),
  properties: () => import("@shikijs/langs/ini"),
  java: () => import("@shikijs/langs/java"),
  javascript: () => import("@shikijs/langs/javascript"),
  js: () => import("@shikijs/langs/javascript"),
  cjs: () => import("@shikijs/langs/javascript"),
  mjs: () => import("@shikijs/langs/javascript"),
  jinja: () => import("@shikijs/langs/jinja"),
  json: () => import("@shikijs/langs/json"),
  json5: () => import("@shikijs/langs/json5"),
  jsonc: () => import("@shikijs/langs/jsonc"),
  jsx: () => import("@shikijs/langs/jsx"),
  julia: () => import("@shikijs/langs/julia"),
  jl: () => import("@shikijs/langs/julia"),
  kotlin: () => import("@shikijs/langs/kotlin"),
  kt: () => import("@shikijs/langs/kotlin"),
  kts: () => import("@shikijs/langs/kotlin"),
  latex: () => import("@shikijs/langs/latex"),
  less: () => import("@shikijs/langs/less"),
  log: () => import("@shikijs/langs/log"),
  lua: () => import("@shikijs/langs/lua"),
  make: () => import("@shikijs/langs/make"),
  makefile: () => import("@shikijs/langs/make"),
  markdown: () => import("@shikijs/langs/markdown"),
  md: () => import("@shikijs/langs/markdown"),
  nginx: () => import("@shikijs/langs/nginx"),
  nix: () => import("@shikijs/langs/nix"),
  "objective-c": () => import("@shikijs/langs/objective-c"),
  objc: () => import("@shikijs/langs/objective-c"),
  "objective-cpp": () => import("@shikijs/langs/objective-cpp"),
  perl: () => import("@shikijs/langs/perl"),
  php: () => import("@shikijs/langs/php"),
  pkl: () => import("@shikijs/langs/pkl"),
  po: () => import("@shikijs/langs/po"),
  pot: () => import("@shikijs/langs/po"),
  potx: () => import("@shikijs/langs/po"),
  powershell: () => import("@shikijs/langs/powershell"),
  ps: () => import("@shikijs/langs/powershell"),
  ps1: () => import("@shikijs/langs/powershell"),
  proto: () => import("@shikijs/langs/proto"),
  protobuf: () => import("@shikijs/langs/proto"),
  python: () => import("@shikijs/langs/python"),
  py: () => import("@shikijs/langs/python"),
  r: () => import("@shikijs/langs/r"),
  rst: () => import("@shikijs/langs/rst"),
  ruby: () => import("@shikijs/langs/ruby"),
  rb: () => import("@shikijs/langs/ruby"),
  rust: () => import("@shikijs/langs/rust"),
  rs: () => import("@shikijs/langs/rust"),
  sass: () => import("@shikijs/langs/sass"),
  scala: () => import("@shikijs/langs/scala"),
  scss: () => import("@shikijs/langs/scss"),
  shellscript: () => import("@shikijs/langs/shellscript"),
  bash: () => import("@shikijs/langs/shellscript"),
  sh: () => import("@shikijs/langs/shellscript"),
  shell: () => import("@shikijs/langs/shellscript"),
  zsh: () => import("@shikijs/langs/shellscript"),
  sql: () => import("@shikijs/langs/sql"),
  "ssh-config": () => import("@shikijs/langs/ssh-config"),
  stylus: () => import("@shikijs/langs/stylus"),
  styl: () => import("@shikijs/langs/stylus"),
  svelte: () => import("@shikijs/langs/svelte"),
  swift: () => import("@shikijs/langs/swift"),
  "system-verilog": () => import("@shikijs/langs/system-verilog"),
  terraform: () => import("@shikijs/langs/terraform"),
  tf: () => import("@shikijs/langs/terraform"),
  tfvars: () => import("@shikijs/langs/terraform"),
  toml: () => import("@shikijs/langs/toml"),
  tsx: () => import("@shikijs/langs/tsx"),
  typescript: () => import("@shikijs/langs/typescript"),
  ts: () => import("@shikijs/langs/typescript"),
  cts: () => import("@shikijs/langs/typescript"),
  mts: () => import("@shikijs/langs/typescript"),
  vb: () => import("@shikijs/langs/vb"),
  cmd: () => import("@shikijs/langs/vb"),
  verilog: () => import("@shikijs/langs/verilog"),
  viml: () => import("@shikijs/langs/viml"),
  vim: () => import("@shikijs/langs/viml"),
  vimscript: () => import("@shikijs/langs/viml"),
  vue: () => import("@shikijs/langs/vue"),
  xml: () => import("@shikijs/langs/xml"),
  yaml: () => import("@shikijs/langs/yaml"),
  yml: () => import("@shikijs/langs/yaml"),
  zig: () => import("@shikijs/langs/zig"),
} as Record<BundledLanguage, DynamicImportLanguageRegistration>;

const bundledThemes = {
  "github-light-default": () => import("@shikijs/themes/github-light-default"),
  "github-dark-default": () => import("@shikijs/themes/github-dark-default"),
} as Record<BundledTheme, DynamicImportThemeRegistration>;

const createHighlighter = /* @__PURE__ */ createBundledHighlighter<BundledLanguage, BundledTheme>({
  langs: bundledLanguages,
  themes: bundledThemes,
  engine: () => createJavaScriptRegexEngine(),
});

const {
  codeToHtml,
  codeToHast,
  codeToTokensBase,
  codeToTokens,
  codeToTokensWithThemes,
  getSingletonHighlighter,
  getLastGrammarState,
} = /* @__PURE__ */ createSingletonShorthands<BundledLanguage, BundledTheme>(createHighlighter);

export {
  bundledLanguages,
  bundledThemes,
  codeToHast,
  codeToHtml,
  codeToTokens,
  codeToTokensBase,
  codeToTokensWithThemes,
  createHighlighter,
  getLastGrammarState,
  getSingletonHighlighter,
};
export type { BundledLanguage, BundledTheme, Highlighter };
