export const BROWSER_PREVIEW_MAX_WEBSOCKET_PENDING_MESSAGES = 256;
export const BROWSER_PREVIEW_MAX_WEBSOCKET_PENDING_BYTES = 1024 * 1024;
export const BROWSER_PREVIEW_MAX_WEBSOCKET_BUFFERED_BYTES = 2 * 1024 * 1024;
export const BROWSER_PREVIEW_PEER_DRAIN_THRESHOLD_BYTES = 512 * 1024;
export const BROWSER_PREVIEW_WEBSOCKET_CONNECT_TIMEOUT_MS = 10_000;
